name: Setup Go Environment

on:
  workflow_call:
    inputs:
      go_version:
        required: true
        type: string
        description: "Go version to use"

    outputs:
      cache_key:
        description: "Cache key for Go modules"
        value: ${{ jobs.setup.outputs.cache_key }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache_key: ${{ steps.generate-cache-key.outputs.cache_key }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Go Version
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go_version }}

      - name: Generate Cache Key
        id: generate-cache-key
        run: |
          cache_key="${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}"
          echo "cache_key=$cache_key" >> $GITHUB_OUTPUT
          echo "Generated cache key: $cache_key"

      - name: Cache Go Modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ steps.generate-cache-key.outputs.cache_key }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Dependencies
        run: go mod download
